# Environment definition file for Conda for ease of install
# To create the environment, run the following command:
# conda env create -f environment.yml
name: stat107
dependencies:
    - python=3.12
    - ipykernel
    - pandas
    - numpy
    - pandas-stubs
    - matplotlib
    - scipy
    - pip:
        - scikit-learn